### ISSUE TITLE
org-mode中使用firefox打开连接

### ISSUE THREAD

**Issue by vipzrx** [LdBeth/Emacs-for-Noobs#2]
我使用的是陈斌的emacs.d配置
他设置的是使用w3m打开org-mode模式中的链接。我是在cygwin下使用emacs，想用firefox打开连接
我lisp代码不好，已经找到了相关的设置地方，不知道该怎么改：

(defadvice org-open-at-point (around org-open-at-point-choose-browser activate)
  (let ((browse-url-browser-function
         (cond
          ;; open with external browser
          ((equal (ad-get-arg 0) '(4)) 'browse-url-generic)
          ;; open with w3m
          (t 'w3m-browse-url))))
    ad-do-it))

firefox的安装路径在
C:\Program Files (x86)\Mozilla Firefox\firefox.exe

另外我希望双击org-mode中的链接，能够打开一个tab页面，现在firefox.exe是打开一个窗口

**Comment by LdBeth** [comment]
我已经提供了一个思路，而且陈斌也已经在配置里加入了支持并给出了说明。

https://github.com/redguardtoo/emacs.d/issues/572#issuecomment-288568879

只要把 exe 的路径加入环境变量就可以了。或者你也可以直接设置 browse-url-firefox-program 的值为浏览器的路径。

如果你想用新窗口打开的话，把 browse-url-firefox-new-window-is-tab 设置为 nil。

这个问题应该也解决了。
